language: node_js
dist: trusty
node_js:
- "7"

env:
  global:
    - CXX=g++-4.8

matrix:
  include:
    - os: linux
      sudo: required
      env: BROWSER=chrome  BVER=stable
    - os: linux
      sudo: required
      env: BROWSER=chrome  BVER=beta
    - os: linux
      sudo: required
      env: BROWSER=chrome  BVER=unstable
    - os: linux
      sudo: false
      env: BROWSER=chrome BVER=54.0.2840.71
    - os: linux
      sudo: false
      env: BROWSER=firefox BVER=stable
    - os: linux
      sudo: false
      env: BROWSER=firefox BVER=beta
    - os: linux
      sudo: false
      env: BROWSER=firefox BVER=unstable
    - os: linux
      sudo: false
      env: BROWSER=firefox BVER=46.0.1
    - os: osx
      sudo: required
      osx_image: xcode9.2
      env: BROWSER=safari BVER=stable
    - os: osx
      sudo: required
      osx_image: xcode11.3
      env: BROWSER=safari BVER=unstable

  fast_finish: true

  allow_failures:
    - os: linux
      sudo: required
      env: BROWSER=chrome  BVER=unstable
    - os: linux
      sudo: false
      env: BROWSER=firefox BVER=unstable

before_script:
  # Need to update dpkg, else Chrome installation will fail
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
      sudo apt-get update && sudo apt-get -y install dpkg;
    fi;
  - ./setup.sh
  - export DISPLAY=:99.0
  - if [ -f /etc/init.d/xvfb ]; then sh -e /etc/init.d/xvfb start; fi

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

notifications:
  email:
  - damon.oehlman@gmail.com

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - g++-4.8
