dist: bionic
language: node_js
node_js:
- 12

env:
  global:
    - DISPLAY=:99.0

matrix:
  include:
    - os: linux
      sudo: false
      env: BROWSER=chrome  BVER=stable
    - os: linux
      sudo: false
      env: BROWSER=chrome  BVER=beta
    - os: linux
      sudo: false
      env: BROWSER=chrome  BVER=unstable
    - os: linux
      sudo: false
      env: BROWSER=chrome BVER=54.0.2840.71
    - os: linux
      sudo: false
      env: BROWSER=firefox BVER=stable
    - os: linux
      sudo: false
      env: BROWSER=firefox BVER=beta
    - os: linux
      sudo: false
      env: BROWSER=firefox BVER=unstable
    - os: linux
      sudo: false
      env: BROWSER=firefox BVER=46.0.1
    - os: osx
      sudo: required
      osx_image: xcode9.2
      env: BROWSER=safari BVER=stable
    - os: osx
      sudo: required
      osx_image: xcode11.2
      env: BROWSER=safari BVER=unstable

  fast_finish: true

  allow_failures:
    - os: linux
      sudo: false
      env: BROWSER=chrome  BVER=unstable
    - os: linux
      sudo: false
      env: BROWSER=firefox BVER=unstable

before_script:
  - Xvfb :99 &
  - ./setup.sh

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

notifications:
  email:
  - damon.oehlman@gmail.com
