language: node_js
node_js:
- "7"

env:
  global:
    - CXX=g++-4.8

matrix:
  - os: linux
    sudo: false
    env: BROWSER=chrome  BVER=stable
  - os: linux
    sudo: false
    env: BROWSER=chrome  BVER=beta
  - os: linux
    sudo: false
    env: BROWSER=chrome  BVER=unstable
  - os: linux
    sudo: false
    env: BROWSER=firefox BVER=stable
  - os: linux
    sudo: false
    env: BROWSER=firefox BVER=beta
  - os: linux
    sudo: false
    env: BROWSER=firefox BVER=unstable
  - os: osx
    sudo: required
    osx_image: xcode8.3
    env: BROWSER=safari BVER=unstable

  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable
    - env: BROWSER=firefox BVER=unstable

before_script:
  - ./setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

notifications:
  email:
  - damon.oehlman@gmail.com

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
